name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        moonbit-version: ['latest', 'nightly']
        moonup-version: ['', '0.5.0']
        exclude:
          - moonup-version: '0.5.0'
            moonbit-version: 'nightly'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Moonup
        uses: ./
        with:
          version: ${{ matrix.moonup-version }}
          moonbit-version: ${{ matrix.moonbit-version }}

      - name: Verify installation
        run: |
          moonup --version
          moon version

  test-mooncakes-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Moonup
        uses: ./
        with:
          mooncakes-username: ${{ secrets.MOONCAKES_USERNAME }}
          mooncakes-token: ${{ secrets.MOONCAKES_TOKEN }}

      - name: Verify mooncakes
        run: moon whoami
